name: Tests

on:
  push:
    branches:
      - master
      - '*.*.*'

  pull_request:
    branches:
      - master
      - '*.*.*'

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9, '3.10' ]
        django-version: [ 20, 21, 22, 30, 31, 32 ]
        exclude:
          - python-version: 3.6
            django-version: 40
          - python-version: 3.8
            django-version: 40

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}


      - name: Run Opensearch in docker
        run: |
          docker-compose up -d
          sleep 30

      - name: Install Tox and any other packages
        run: |
          pip install tox
      - name: Run Tox (Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }})
        run: tox -e py-django${{ matrix.django-version }}

      - name: Upload coverage to Codecov
        if: matrix.python-version == 3.10 && matrix.django-version == 32
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml

  publish:
    needs: test
    if: github.event_name == 'release' && github.event.action == 'created'
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10

      - name: Creating Built Distributions
        run: python setup.py sdist

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}
          skip_existing: true
